version: '3'

tasks:
  dev:
    deps: [backend:dev, frontend:dev]

  backend:dev:
    cmds:
      - go run . 
    silent: true
    dir: ./backend

  backend:build:
    cmds:
      - go build -o bin/ci
    silent: true
    dir: ./backend

  frontend:dev:
    cmds:
      - pnpm dev 
    silent: true
    dir: ./frontend
